# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tftg256-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/Study/FPGA/Project/cal_test1/cal_test1.cache/wt [current_project]
set_property parent.project_path F:/Study/FPGA/Project/cal_test1/cal_test1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  f:/Study/FPGA/Project/p_ip_ajxd
  f:/Study/FPGA/Project/p_ip_disp
} [current_project]
update_ip_catalog
set_property ip_output_repo f:/Study/FPGA/Project/cal_test1/cal_test1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  F:/Study/FPGA/Project/cal_test1/cal_test1.srcs/sources_1/new/debounce_sw.v
  F:/Study/FPGA/Project/cal_test1/cal_test1.srcs/sources_1/new/process1.v
  F:/Study/FPGA/Project/cal_test1/cal_test1.srcs/sources_1/new/uart_send.v
  F:/Study/FPGA/Project/cal_test1/cal_test1.srcs/sources_1/new/uartsend.v
  F:/Study/FPGA/Project/cal_test1/cal_test1.srcs/sources_1/new/v_ajxd.v
  F:/Study/FPGA/Project/cal_test1/cal_test1.srcs/sources_1/new/v_disp1.v
  F:/Study/FPGA/Project/cal_test1/cal_test1.srcs/sources_1/new/vga_disp.v
  F:/Study/FPGA/Project/cal_test1/cal_test1.srcs/sources_1/new/vga_dri.v
  F:/Study/FPGA/Project/cal_test1/cal_test1.srcs/sources_1/new/v1.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/Study/FPGA/Project/cal_test1/cal_test1.srcs/constrs_1/new/cons2.xdc
set_property used_in_implementation false [get_files F:/Study/FPGA/Project/cal_test1/cal_test1.srcs/constrs_1/new/cons2.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7a35tftg256-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_2_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
